language: java

jdk:
- oraclejdk8

cache:
  directories:
  - "$HOME/.m2"
  
after_success:
- mvn clean cobertura:cobertura coveralls:report

env:
  global:
  - secure: JRVwYwEM0ITqsSu6ok8qsEkZjMIkWAz++wU9YxXdo8PPOzScrazUWXqEVchWl0ajMnu42eDERQasulIEg/di8LcPSz2iX7oWNz/7r/wqVnmMIpgeqnO7uR+FlCCjpfjiadq9IBIvK09kgagAdOFnsT7bXiCBFJx/MsMixupNcAWlf7ixQuLHxmA4ZC7bZ8KPmuXICulvqjSX6XQIgVpOA6GtohvAVuKp0trluDLVlikkhaXlg8WmaFN/NytDZGvEPEvUrbhmdnO53a9Q2hDD5ZD5JfOUudRtVEKx/f06tXuWjiPAlsO4nXW3eYovGSj+LDqtg9PGWtH5JFam1BWJodnZpBPrwhYhGqMJOeMu5FVey0uUSyDLIrJYJMWRLZ9VMxgNmj2lfJKJKrRpHuDyM4G80euxzB9zQWpZQsQsymdK1kIyVTuwMadzFQ421767EzQ0yJmRjyAT8zxNEGSg29LXCjFkTMHj8aNnf57CD4ublGOPdwrjAgKu/ryqT/hcTp1D5dsjLD8yElxagVLGtQh6vkWbaLdPEC7K0U74RLayAQdvqwxoe4p52Mp7N3FlioXFFhrFcyfcdBLD2K0+fAgDVZiFh/lyeSastT7BY/fpBPuT/rxN2DjVQ7srikeiRHKgF3GYGqWU196ZJ24MZRzTA5NblowpTXjdG+L66/c=
  - secure: mIgc+Bs0su5jzDPQMmFmqBpkf795YYRTd0KCeNLPiqmyKIk+RoIVKzHdseraSbTjJ33kgfrX9UTnDdNAPSF2ZebsvRwwtAwg/pLiohGeOgeiPxaardB084rzzrc4qde6grZmSxciqHXg6kRqL3O1sgvA/zYHuJ84nsdL2nRY/kuS6JmhWpMu9UjyPUAcSlKyoanKc18X7qOJ101Zxu8pdrUPTUrZvrExjsEjzPBvXF7Mfj3nFb940ZmPdoM7K7N5ljqjIouJt6mqKlKRg62lQmyyT7+C2FghZa6nLHBzNO4l2rwyiT0xf2SIFbOJH/6ywfHMd6l5OFVGK8tyfDaDmXEewwkw0O/I/LVoKergfuVKp7k5sqJHkpvRA09pWOuKqmMjVb5BxUEPaqCMC9MOjEm4FOarFHyBg+MyAEUAqjzIYVinOATWEPYt7lkGno5JDuBLSU3M90b+GlvRQnc6PP6iVvMjd4FNM5oERh0v747onICL5dWePfi7mZSXfOhN0ZH4o91uF++OTFIJcB4bh418oGLRZ+TA9sLjAdcaVcEiDXPkkq9855584Y6U1poJhlHr6oDQl9nMPlbjEJ9ZbO9l/GAuAyJuQWg5j65dZuuEvt8xcJoFESzZdLt/xvHiqgJalFUWZ/pP9C+m+nYRv5B06OuZWr8cmf9P7+bJ7DE=
  - secure: Cjb6hys9F3pPA2SIhEMh/fpoXR5zjdhsh1Lejke/zfB2VXmdHm8mqVFpRxCM1zd6JT0n2u1s5WYEbU8vWgfnr5NnOlvohQZJwLPQ1liJynsGX5iSp8ZOJS83utVqdeCzT7Z+JJUQ+RobVDkGMWK2vWEXcSNdnnwfMV40i5Mp/HijqdQFFzcX+R7aHNLUv7wNvjUW0Fi/gmBzk6oiuH+XWuUvKANUgAGx/gWicwgqAqq0zwbJzJzl/7op5Zs72Bq86tYZz8ylYdjoCFpcAHwn/oTuBwXVDwyVBnKdr7rLPee4S1hWj1bk37GONRKCacK9W3iqQ+/10nOlIAt/VUw0hMGcLu/xclGPF2a81E4ZhosLddsrksaPIGtwVK3rbGucuP1I7NyY/PiP45ep4Mbwnql+Cyb80mP9UdSqfb8FESU5Rb6fd2P5JjGlVjKwm6CcpfFrHmkXVJEv45ZtjYEK4BgdWfLo/sOu3PGFBRPpaNjPe95mjDgzHtPW3bmI7ePWcmBfQIkIeGzkw29Q3z0W40ez9Zrx71faRW3VRhff+VfLIP2mKwgSwQV/3hHlZJwcxDu+4LoUo2WOlgOUkThZ6tAnOrgDTjvBm5wBYm3MtzkVBEqwaLYA/T4sknFzVm/AI1Cmlws2ikvQA25tzOyy3DSW0EZBVxV6eRtEyf96iHo=
  
script: make build

deploy:
  provider: script
  script: make travis-deploy
  on:
    tags: true
